### ISSUE TITLE
Instructions for compiling it with rust please. 

### ISSUE THREAD

**Issue by shirishag75** [EEVV/leafpad3#1]
There doesn't seem to be a readme.md to know how to compile it or whatever dependencies are needed to compile leafpad3 :(

**Comment by shirishag75** [comment]
what is the below command supposed to do, it's not clear - 

`curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly`

maybe you can add why this command is needed and what it is supposed to do ?

looks like rust uses something called crates which is similar to how maven uses pom.xml to download dependencies. 

Wouldn't it be nicer/better to have versioned dependencies and to update the same if and when you are going to add new functionality to leafpad3 ?

**Comment by EEVV** [comment]
```
curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly
```
This command installs the Rust compiler and Crates package/dependency manager. The dependencies are versioned in the `Cargo.toml` file, but I'm not too sure what you mean by your last question there...

**Comment by shirishag75** [comment]
> ```
> curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly
> ```
> 
> This command installs the Rust compiler and Crates package/dependency manager. The dependencies are versioned in the `Cargo.toml` file, but I'm not too sure what you mean by your last question there...

I thought so.  Your answer answered my query anyway thank you. I will try and get back to you as to what the results are. For now closing this bug.
